<?php         
$this->title = "Shopping Cart";
$this->headTitle($this->title);
?>

<?php if($this->cart->isEmpty()): ?>
    Your cart is empty!
<?php else: ?>
    <table width="500">
        <tr><td width="400">&nbsp;</td><td width="50">Price</td><td>Quantity</td></tr>
    <?php foreach($this->cart->getItems() as $item): ?>
        <tr>
            <td>
                <b><?= $this->cartInfo[$item['pid']]['itemName']; ?></b><br>
                <?= $this->cartInfo[$item['pid']]['itemDescription']; ?><br>
                <?= ($this->cartInfo[$item['pid']]['quantity'] > 0) ? 'In Stock' : 'Backorder'; ?><br><br>
                <small><a href="<?= $this->url(array('action'=>'delete','pid'=> $item['pid'])); ?>">Delete</a></small>
            </td>
            <td align="center">                
                <b><?= money_format('$%i',$this->cartInfo[$item['pid']]['price']); ?> </b>                
            </td>
            <td align="center">
                <form method="post" action="<?= $this->url(array('action'=>'changeqty','pid'=> $item['pid'])); ?>">
                    <select name="qty" onChange="this.form.submit();">
                        <?php for($i=0; $i<=($item['q']>9 ? $item['q'] : 9); $i++): ?>
                            <option value="<?= $i; ?>"<?= ($i==$item['q']) ? ' selected' : ''; ?>><?= $i; ?></option>
                        <?php endfor; ?>
                    </select>
            </td>
        </tr>                    
    <?php endforeach; ?>
    </table>
<?php endif; ?>
    <BR>
    <BR>DEBUG: <a href="<?= $this->url(array('module'=>'default','controller'=>'cart','action'=>'add','pid'=> 1), null, true); ?>">Add an item!</a>
    
    