<?php         
$this->title = "Shopping Cart";
$this->headTitle($this->title);
?>

<?php if($this->cart->isEmpty()): ?>
    Your cart is empty!
<?php else: ?>
    <ul>
    <?php foreach($this->cart->getItems() as $item): ?>

        <li>
            <?= $this->cartInfo[$item['pid']]['itemName']; ?> - 
            <?= money_format('$%i',$this->cartInfo[$item['pid']]['price']); ?> 
            (Quantity: <?= $item['q']; ?>)
            <a href="<?= $this->url(array('action'=>'delete','pid'=> $item['pid'])); ?>">Delete</a>
        </li>

    <?php endforeach; ?>
    </ul>
<?php endif; ?>
    <BR>
    <a href="<?= $this->url(array('action'=>'add','pid'=> 1)); ?>">Add an item!</a>
    <BR>
    Debug: <?= $this->cart; ?>
            <?= print_r($this->cartInfo,1); ?>  
    
    