<?php
/**
 * Created by PhpStorm.
 * User: Tyler
 * Date: 10/26/14
 * Time: 11:30 AM
 */
$this->title = "Browse Items";
$this->headTitle($this->title);
//echo $this->form;
?>
<?php if (count($this->paginator)): ?>
<table>
    <tr>
        <th>Name</th>
        <th>Price</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach($this->paginator as $item): ?>

        <tr>
            <td><?php echo $item->itemName;?></td>
            <td><?php echo $item->price;?></td>
            <td><?php echo '<input type="button" value="Add to Cart" alt="Add to Cart">';?></td>
        </tr>

    <?php endforeach; ?>
</table>
<?php endif; ?>