<?php         
$this->title = "Browse Items";
$this->headTitle($this->title);
?>

<html>
<body>
<h1>Books</h1>
<ul><?php

    // Create a select query. $db is a Zend_Db_Adapter object, which we assume
    // already exists in your script.
    //$db = Zend_Registry::get('bookstore');
    //$select = $db->select('*')->from('inventory');
    // Get a Paginator object using Zend_Paginator's built-in factory.
    //$paginator = Zend_Paginator::factory($select);

    // Create an array with numbers 1 to 100
    $data = range(1, 100);

    // Get a Paginator object using Zend_Paginator's built-in factory.
    $paginator = Zend_Paginator::factory($data);

    //Configure Paginator
    $paginator->setDefaultItemCountPerPage( 5 );
    $paginator->setCurrentPageNumber(1);

    // Render each item for the current page in a list-item
    foreach ($paginator as $item) {
        echo '<li>' . $item . '</li>';
    }

    ?></ul>




</body>
</html>