<?php
$this->title = "Item Details";
$this->headTitle($this->title);

//get item details
$link = "$_SERVER[REQUEST_URI]";

//get id from url
$id = substr( $link, strrpos( $link, '/' )+1 );

?>

<?php if (count($this->paginator)): ?>
    <table>
        <tr>

            <th>Name</th>
            <th>Price</th>
            <th>&nbsp;</th>
            <th>Item Details</th>
        </tr>
        <?php foreach($this->paginator as $item): ?>
            <?php if ($item->id == $id): ?>
                <tr>
                    <td><?php echo $item->itemName;?></td>
                    <td><?php echo $item->price;?></td>
                    <td><?php echo '<input type="button" value="Add to Cart" alt="Add to Cart">';?></td>
                    <td></td>
                    <td><?php echo $item->itemDescription;?></td>
                </tr>
            <?php endif; ?>
        <?php endforeach; ?>
    </table>
<?php endif; ?>