<?php
$this->title = "Item Details";
$this->headTitle($this->title);

?>
<?php if(!empty($this->item['imageURL'])): ?>
    <img src="<?= $this->item['imageURL']; ?>" align="left" width="25%" height="25%">
<?php endif; ?>
<strong style="font-size:20px;"><?= $this->item['itemName'];?></strong><br>
<b>Price:</b> <?= $this->item['price'];?><br>
<b>Description:</b> <?= $this->item['itemDescription'];?><br>
   
<br>
<center>
<a href="<?= $this->url(array('module'=>'default','controller'=>'cart','action'=>'add','pid'=> $this->item['itemID']), null, true); ?>">Add to Cart!</a>
