<?php
/**
 * Created by PhpStorm.
 * User: Tyler
 * Date: 10/26/14
 * Time: 11:30 AM
 */
$this->title = "Browse Items";
$this->headTitle($this->title);
//echo $this->form;
?>
<?php if (count($this->paginator)): ?>
    <table>
        <tr>

            <th>Name</th>
            <th>Item Details</th>
            <th>Price</th>
            <th>&nbsp;</th>
            <th>Sort by: <a href="/item/price">Price</a> | <a href="/item/category">Category</a> </th>
        </tr>
        <?php foreach($this->paginator as $item): ?>

            <tr>
                <td><?php echo $item->itemName;?></td>
                <td><?php echo '<a href="'.$this->url(array('module' => 'default','controller'=>'item','action'=>'detail',$item->id), null, TRUE);?>">Details</a></td>
                <td><?php echo $item->price;?></td>
                <td><?php echo '<a href="'.$this->url(array('module'=>'default','controller'=>'cart','action'=>'add','pid'=>$item->id), null, true); ?>">Add to Cart!</a></td>
                <td><?php echo $item->categoryID;?></td>

            </tr>

        <?php endforeach; ?>
    </table>
<?php endif; ?>

<?php echo $this->paginationControl($this->paginator, 'Sliding', 'my_pagination_control.phtml'); ?>

